# Generated by Django 3.1.5 on 2022-08-19 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oportal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opportunity',
            options={'ordering': ['role'], 'permissions': (('can_add_opportunity', 'Add opportunity'), ('can_edit_opportunity', 'Edit opportunity'), ('can_delete_opportunity', 'Delete opportunity')), 'verbose_name_plural': 'Opportunities'},
        ),
    ]
